### ISSUE TITLE
Nothing to do with this program, but.....

### ISSUE THREAD

**Issue by NovaCygni** [hanetzer/SecureCraftProtect#3]
Why the fuck did you put in a Orphan request for the ONLY Working version of CKM-Tether from the AUR? Were you smoking crack or something at the time? the version that was on the AUR worked perfect unlike the AUR-Mirror backup everyone is stuck using now which has broken code due to a mix of Python2 and Python3 code in it.... thats a proper fucktarded idiotic thing to do, I was going to let it drop under the impression the only reason a normal person would do that was 1) If the program was broken, which it wasnt or 2) You wanted to maintain and adopt the project yourself.... which apparently you didnt, oh btw the maintainer didnt put a real Email address because it wasnt required as he checked the bug-reports and GENUINE ones got resolved (\* Not idiots who couldnt read the fuckin manual *)... He now refuses to have anything to do with the project because of the pathetic way some CUNT decided to have it pulled from the AUR when it worked perfectly.... 

So, in reflection, your a 100% cunt, PRAY you keep your OpSec on form, your a marked man..... Cunt...

**Comment by NovaCygni** [comment]
For anyone whos interested turns out this guy ntzrmtthihu777(Marty Plummer) Is a well known convicted pedophile, http://www.texaspredators.com/SexOffender.aspx?oid=22969
He repeatedly raped a 6yr old girl...

**Comment by hanetzer** [comment]
I'll ignore the second comment for now. In any case, I put in an orphan request in order to update it for the very reason you stated, that it was horridly broken, and simply did not work at all. I had an update for it, but lost interest due to no longer needing it. However, I can still stick a good one on the aur quite quickly.
